"""Added Column rfid in the users table

Revision ID: 1191c21efd20
Revises: 2a762864547f
Create Date: 2025-12-03 21:57:45.572370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1191c21efd20'
down_revision = '2a762864547f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfid', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rfid')

    # ### end Alembic commands ###
