"""Update teacher_attendances: add check_in_at and check_out_at, remove created_at and updated_at

Revision ID: 2a762864547f
Revises: bfd69e33fc87
Create Date: 2025-11-01 12:48:52.437069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a762864547f'
down_revision = 'bfd69e33fc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_at', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('check_out_at', sa.Time(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('check_out_at')
        batch_op.drop_column('check_in_at')

    # ### end Alembic commands ###
