"""add father mother and group to students

Revision ID: 5cacdd6b176a
Revises: 6f3600c42bb4
Create Date: 2025-12-26 10:06:43.561725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cacdd6b176a'
down_revision = '6f3600c42bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mother_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('group', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('group')
        batch_op.drop_column('mother_name')
        batch_op.drop_column('father_name')

    # ### end Alembic commands ###
