"""Add Column timestamp in teachers table

Revision ID: 6e95a4f97cc9
Revises: bace72063e3e
Create Date: 2025-10-09 05:42:12.089072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e95a4f97cc9'
down_revision = 'bace72063e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
