"""add k_name to students and teachers

Revision ID: 6f3600c42bb4
Revises: 1191c21efd20
Create Date: 2025-12-16 13:34:43.901104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3600c42bb4'
down_revision = '1191c21efd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('k_name', sa.String(length=200), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('k_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('k_name')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('k_name')

    # ### end Alembic commands ###
