"""Add trx_id column to transactions

Revision ID: 72b4adec5b4e
Revises: b9605d9590ab
Create Date: 2025-10-29 19:24:52.792311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b4adec5b4e'
down_revision = 'b9605d9590ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trx_id', sa.String(length=100), nullable=True, comment='bKash executed transaction ID'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('trx_id')

    # ### end Alembic commands ###
