"""Add merchant_invoice_number to Transaction

Revision ID: b9605d9590ab
Revises: 7d3701ac780e
Create Date: 2025-10-28 19:44:02.384594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9605d9590ab'
down_revision = '7d3701ac780e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_invoice_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('merchant_invoice_number')

    # ### end Alembic commands ###
