"""Add Column designation in teachers table

Revision ID: ce928308a2ae
Revises: 6e95a4f97cc9
Create Date: 2025-10-09 16:11:32.252846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce928308a2ae'
down_revision = '6e95a4f97cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('designation')

    # ### end Alembic commands ###
